laravel/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index');
    Route::post('/',[RoleController::class, 'store'])->name('store');
    Route::get('/create',[RoleController::class, 'create'])->name('create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy');
});

Route::name('users.')->prefix('users')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index');
    Route::post('/',[UserController::class, 'store'])->name('store');
    Route::get('/create',[UserController::class, 'create'])->name('create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy');
});

Route::prefix('categories')->name('categories.')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index');
    Route::post('/',[CategoryController::class, 'store'])->name('store');
    Route::get('/create',[CategoryController::class, 'create'])->name('create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy');
});


Route::prefix('products')->name('products.')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index');
    Route::post('/',[ProductController::class, 'store'])->name('store');
    Route::get('/list',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show');
    Route::get('/create',[ProductController::class, 'create'])->name('create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy');
});

laravel/app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name'
    ];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function hasPermissions($permissionName)
    {
        return $this->permissions->contains('name', $permissionName);
    }

    public function attachPermission($permissionId)
    {
        return $this->permissions()->attach($permissionId);
    }

    public function detachPermission()
    {
        return $this->permissions()->detach();
    }

    public function syncPermission($permissionId)
    {
        return $this->permissions()->sync($permissionId);
    }
}

laravel/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use App\Services\RoleService;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected $roleService;

    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }

    public function index()
    {
//        $roles = $this->roleService->all();
        $roles = Role::latest('id')->paginate(5);
        return view("admin.roles.index", compact('roles'));
    }

    public function show($id)
    {
        $role = $this->roleService->findById($id);
        return view("admin.roles.show", compact('role'));
    }

//    /**
//     *show the form creating a new resource.
//     *
//     *@return  \Illuminate\Http\Response
//     */


    public function create()
    {
        $permission = Permission::all()->groupBy('group_name');
//        dd($permission);
        return view("admin.roles.create", compact('permission'));
    }

    public function store(CreateRoleRequest $request)
    {

        $this->roleService->store($request);
        return redirect()->route('roles.index')->with('message', "Create role successfully.");
    }

    public function edit($id)
    {
        $role = $this->roleService->findById($id);
        $group_permission = $this->roleService->getPermissionsByGroup($id);

        return view("admin.roles.edit", compact('role','group_permission'));
    }

    public function update(UpdateRoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route("roles.index")->with("message", "Update role successfully!");
    }

    public function destroy($id)
    {
        $this->roleService->destroy($id);
        return redirect()->back()->with("message", "Delete role successfully.");
    }
}

laravel/resources/views/admin/roles/create.blade.php
@extends("admin.Layouts.dashboard")
@section('title', 'Create Roles')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Create Role</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('roles.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf

                                <div class="input-group input-group-static mb-4">
                                    <label>Name</label>
                                    <input type="text"  value="{{ old('name')}}"  name="name" class="form-control">

                                    @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="input-group input-group-static mb-4">
                                    <label>Display Name</label>
                                    <input type="text"  value="{{ old('display_name')}}" name="display_name" class="form-control">

                                    @error('display_name')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror

                                </div>

                            <div class="input-group input-group-static mb-4">
                                <label for="exampleFormControlSelect1" name="group" class="ms-0">Group</label>
                                <select class="form-control" id="exampleFormControlSelect1">
                                    <option value="system">System</option>
                                    <option value="user">User</option>

                                </select>
                                @error('group')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>

                                <div class="form-group">
                                    <label for="">Permission</label>
                                    <div class="row">
                                        @foreach($permission as $group_name => $values)
                                            <div class="col-4">

                                                <h4> {{ $group_name }}</h4>

                                                @foreach($values as $value)
                                                    <div class="form-check">
                                                        <input id="box-{{ $value->id }}" class="form-check-input" name="permission_id[]" value="{{ $value->id }}" type="checkbox"
                                                            {{ (is_array(old("permission_id")) and in_array($value->id, old("permission_id"))) ? 'checked' : '' }}/>
                                                        <label class="custom-control-label"  for="customCheck1" {{ $value->id }}">{{ $value->display_name }}</label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        @endforeach

                                    </div>
                                </div>
                                <button type="submit" class="btn btn-submit btn-primary">Create</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/admin/roles/edit.blade.php
@extends("admin.Layouts.dashboard")
@section('title', 'Roles')
@section("content")

    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h1 class="page-title">Update Role</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('roles.update',$role->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="modal-body">
{{--                            @include('admin.layouts.form-errors')--}}
                            <div class="mb-3">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" value="{{ $role->name }}" placeholder="Name">
                            </div>
                            <div class="mb-3">
                                <label>Display Name</label>
                                <input type="text" name="display_name" class="form-control" value="{{ $role->display_name }}" placeholder="Display name">
                            </div>
                            @if($role->name != "super-admin")
                                <div class="mb-3 row">
                                    <label>Permission</label>
                                    <div class="form-check">
                                        <input class="form-check-input" id="all" type="checkbox" />
                                        <label for="all">Select all</label>
                                    </div>
                                    @foreach($group_permission as $group => $values)
                                        <div class="col-sm-2">
                                            {{ $group }}
                                            @foreach($values as $value)
                                                <div class="form-check">
                                                    <input id="box-{{ $value->id }}" class="form-check-input" name="permission_id[]" value="{{ $value->id }}" type="checkbox"
                                                        {{$role->permissions->contains('id',$value->id) ? 'checked' : ''}}/>
                                                    <label class="custom-control-label" for="customCheck1-{{ $value->id }}">{{ $value->display_name }}</label>
                                                </div>
                                            @endforeach
                                        </div>
                                    @endforeach
                                </div>
                            @endif
                        </div>
                        <div class="modal-footer">
                            <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                            <button type="submit" class="btn btn-primary btn-button">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

@push('scripts')
    <script src="{{asset('js/role.js')}}"></script>
@endpush

laravel/resources/views/admin/roles/index.blade.php
@extends("admin.Layouts.dashboard")
@section('title', 'Roles')
@section("content")
    <div class="card">
        @if(session('message'))
            <div>
                <h4 class="text-primary">{{ session('message') }}</h4>
            </div>
        @endif
        <div style="padding-left: 1%">
            <h1>Role List</h1>
            <div>
                <a href="{{route('roles.create')}}" class="btn btn-primary">Create</a>
            </div>
        </div>
    </div>
        <div>
            <table class="table table-hover">
                <thead  class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Display Name</th>
                        <th>Action</th>

                    </tr>
                </thead>
                @foreach($roles as $role)
                    <tr>
                        <td>{{ $role->id }}</td>
                        <td>{{ $role->name }}</td>

                        <td>{{ $role->display_name }}</td>
                        <td>
                            <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-success">Edit</a>
                            <a href="{{ route('roles.show', $role->id) }}" class="btn btn-warning">Show</a>
                            <form action="{{ route('roles.destroy', $role->id) }}" method="post" style="display: inline">
                                @csrf
                                @method('delete')
                                <button  class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
            {{$roles->links()}}
        </div>

    </div>
@endsection

@push('scripts')
    <script src="{{asset('js/role.js')}}"></script>
@endpush

laravel/resources/views/admin/roles/show.blade.php
@extends("admin.Layouts.dashboard")
{{--@extends("layouts.app")--}}
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail role {{ $role->name }}</h2>

            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $role->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $role->name }}</dd>
                            <dt class="col-sm-4">Display name :</dt>
                            <dd class="col-sm-8">{{ $role->display_name }}</dd>
                            @if($role->name != "super-admin")
                                <dt class="col-sm-4">Permission :</dt>
                                <dd class="col-sm-8">
                                    <div class="row">
                                        @foreach($role->permissions as $item)
                                            <div class="col-sm-4">
                                                <span class="badge bg-success">{{ $item->display_name }}</span>
                                            </div>
                                        @endforeach
                                    </div>
                                </dd>
                            @endif
                        </dl>
                    </div>

                </div><br>
                <div>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection