laravel/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index');
    Route::post('/',[RoleController::class, 'store'])->name('store');
    Route::get('/create',[RoleController::class, 'create'])->name('create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy');
});

Route::name('users.')->prefix('users')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index');
    Route::post('/',[UserController::class, 'store'])->name('store');
    Route::get('/create',[UserController::class, 'create'])->name('create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy');
});

Route::prefix('categories')->name('categories.')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index');
    Route::post('/',[CategoryController::class, 'store'])->name('store');
    Route::get('/create',[CategoryController::class, 'create'])->name('create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy');
});


Route::prefix('products')->name('products.')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index');
    Route::post('/',[ProductController::class, 'store'])->name('store');
    Route::get('/list',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show');
    Route::get('/create',[ProductController::class, 'create'])->name('create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy');
});

laravel/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'parent_id',
        'slug'
    ];

    public $timestamps = false;

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

}

laravel/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Requests\Category\UpdateCategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;

class CategoryController extends Controller
{

    protected  $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $listCategories = $this->categoryService->all();
        return view("admin.categories.index", compact('listCategories'));
    }

    public function show($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view("admin.categories.show", compact('category'));
    }

    public function create()
    {
        $category = $this->categoryService->all();
        return view("admin.categories.create",  compact('category'));
    }

    public function store(CreateCategoryRequest $request)
    {
        $this->categoryService->store($request);

        return redirect()->route('categories.index')->with('message', "Create Category Successfully!.");
    }


    public function edit($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view("admin.categories.edit", compact('category'));
    }

    public function update(UpdateCategoryRequest $request, $id)
    {
        $this->categoryService->update($request, $id);
        return redirect()->route("categories.index")->with("message", "Update Category Successfully!");
    }

    public function destroy($id)
    {
        $this->categoryService->destroy($id);
        return redirect()->route("categories.index")->with("message", "Delete Category Successfully!");
    }
}

laravel/resources/views/admin/categories/create.blade.php
@extends('admin.Layouts.dashboard')
@section("content")
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Create Category</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="modal-body">

                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" name="name" value="{{ old("name") }}" class="form-control" placeholder="Name">
                                    @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <label>Category Parent</label>
                                    <select name="parent_id" class="form-control col-sm-4" style="width: 200px">
                                        <option value="0">Category option</option>
                                        @foreach($category as $item)

                                                <option value="{{ $item->id }}" {{ old("parent_id") == $item->id ? "selected" : '' }}>{{ $item->name }}</option>

                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                                <button type="submit" class="btn btn-primary btn-button">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

laravel/resources/views/admin/categories/edit.blade.php
@extends('admin.Layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Update Category</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('categories.update',$category->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="modal-body">
{{--                                @include('admin.layouts.form-errors')--}}
                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $category->name }}" placeholder="Name">
                                </div>

                                <div class="mb-3">
                                    <label>Category Parent</label>
                                    <select name="parent_id" class="form-control col-sm-4" style="width: 200px">
                                        <option value="0">Category option</option>
                                        @foreach($categories as $item)
                                            @if($item->parent_id == 0)
                                                <option value="{{ $item->id }}" {{ $category->name ===  $item->name ? 'disabled' : ''}} {{ $category->parent_id == $item->id ? 'selected' : '' }}>{{ $item->name }}</option>
                                            @endif
                                        @endforeach

                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                                <button type="submit" class="btn btn-primary btn-button">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/admin/categories/index.blade.php
@extends("admin.Layouts.dashboard")
@section("content")
    <div class="container-fluid">

        <!-- start page title -->
        @if(session('message'))
            <div>
                <h4 class="text-primary">{{ session('message') }}</h4>
            </div>
        @endif

        <div style="padding-left: 1%">
            <h1>Categories List</h1>
            <div>
                <a href="{{route('categories.create')}}" class="btn btn-primary">Create Categories</a>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>

                                    <th style="width: 85px;text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($listCategories) != 0)
                                    @foreach($listCategories as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->name }}</td>

                                            <td>
                                                <a href="{{route('categories.edit', $item->id)}}" class="btn btn-success">Edit</a>
                                                <a href="{{ route('categories.show', $item->id) }}" class="btn btn-warning">Show</a>
                                                <form action="{{ route('categories.destroy', $item->id) }}" method="post" style="display: inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button  class="btn btn-danger">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $listCategories->appends(request()->all())->links() }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    @push('scripts')
        <script src="{{asset('js/user.js')}}"></script>
    @endpush
@endsection

laravel/resources/views/admin/categories/show.blade.php
@extends("admin.Layouts.dashboard")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail cate {{ $category->name }}</h2>

            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $category->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $category->name }}</dd>
                            <dt class="col-sm-4">Slug :</dt>
                            <dd class="col-sm-8">{{ $category->slug }}</dd>
                            @if($category->parent != null)
                                <dt class="col-sm-4">Category parent :</dt>
                                <dd class="col-sm-8">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <span class="badge bg-success">{{ $category->parent->name }}</span>
                                        </div>
                                    </div>
                                </dd>
                            @endif
                        </dl>
                    </div>
                </div>
                <div><br>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection