laravel/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index');
    Route::post('/',[RoleController::class, 'store'])->name('store');
    Route::get('/create',[RoleController::class, 'create'])->name('create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy');
});

Route::name('users.')->prefix('users')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index');
    Route::post('/',[UserController::class, 'store'])->name('store');
    Route::get('/create',[UserController::class, 'create'])->name('create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy');
});

Route::prefix('categories')->name('categories.')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index');
    Route::post('/',[CategoryController::class, 'store'])->name('store');
    Route::get('/create',[CategoryController::class, 'create'])->name('create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy');
});


Route::prefix('products')->name('products.')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index');
    Route::post('/',[ProductController::class, 'store'])->name('store');
    Route::get('/list',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show');
    Route::get('/create',[ProductController::class, 'create'])->name('create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy');
});

laravel/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'price',
        'quantity',
        'description',
        'image',
    ];

    public $timestamps = false;

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
    public function attachCategory($categoryId)
    {
        return $this->categories()->attach($categoryId);
    }

    public function syncCategory($categoryId)
    {
        return $this->categories()->sync($categoryId);
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeWithMinPrice($query, $minPrice)
    {
        return $minPrice ? $query->where('price', '>=', $minPrice) : null;
    }

    public function scopeWithMaxPrice($query, $maxPrice)
    {
        return $maxPrice ? $query->where('price', '<=', $maxPrice) : null;
    }

    public function scopeWithCategoryName($query, $categoryId)
    {
//        return $categoryId ? $query->whereHas('categories', function ($q) use ($categoryId) {
//            $q->where('category_id', $categoryId);
//        }) : null;
        return $categoryId ? $query->whereHas('categories', fn($q) => $q->where('category_id', $categoryId)) : null;
    }

    public function getImageAttribute($image)
    {
        return $image ? asset("upload/images/products/". $image) : asset("upload/images/default.jpg");
    }

}

laravel/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\UpdateProductRequest;
use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Resources\Product\ProductResource;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    protected $productService;
    protected $categoryService;

    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        $categories = $this->categoryService->all();
//        dd($categories);
        $products= $this->productService->all();
        return view("admin.products.index",compact('products','categories'));
    }

    public function list(Request $request)
    {
        $products = $this->productService->search($request);
        return view("admin.products.list", compact('products'));
    }

    public function show($id)
    {

        $product = $this->productService->findById($id);
       return response()->json([
        'data' => $product,
//        'message' => $message
    ], 200);
    }

    public function create()
    {
        $categories = $this->categoryService->all();
        $product = $this->productService->all();
        return view("admin.products.create", compact('product', 'categories'));//sửa ở đây đê dm!
    }

    public function store(CreateProductRequest $request)
    {
        $product = $this->productService->store($request);
        $productResource = new ProductResource($product);
        return $this->sentSuccessResponse($productResource, 'Create Product success.', Response::HTTP_CREATED);
    }

    public function edit($id)
    {
        $product = $this->productService->findById($id);
        return view("admin.products.edit", compact('product'));
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $product = $this->productService->update($request, $id);
        return $this->sentSuccessResponse($product, 'Update product success.', Response::HTTP_OK);
    }

    public function destroy($id)
    {
        $this->productService->destroy($id);
        return $this->sentSuccessResponse('', 'Delete product success.', Response::HTTP_OK);
    }
}

laravel/resources/views/admin/products/create.blade.php
{{--@extends('admin.Layouts.dashboard')--}}
{{--@section('content')--}}

    <div id="modal-form-create" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="text-center mt-2 mb-4">
                        <h2 class="page-title text-danger">Create Product</h2>
                        <hr>
                    </div>
                    <form data-action="{{ route('products.store') }}" id="addProductForm" method="POST" class="ps-3 pe-3" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label>Name</label>
                            <input type="text" name="name" id="name" class="form-control" placeholder="Name">
                            <div class="text-danger error error-name"></div>
                        </div>
                        <div class="mb-3">
                            <label>Price</label>
                            <input name="price" id="price" class="form-control" placeholder="Price">
                            <div class="text-danger error error-price"></div>
                        </div>
                        <div class="mb-3">
                            <label>Description</label>
                            <input type="text" name="description" id="description" class="form-control" placeholder="Description">
                            <div class="text-danger error error-description"></div>
                        </div>
                        <div class="mb-3">
                            <label>Quantity</label>
                            <input name="quantity" id="quantity" class="form-control" placeholder="Quantity">
                            <div class="text-danger error error-quantity"></div>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Image</label>
                            <input type="file" name="image" class="form-control image" id="image">
                            <div class="show-image" style="width: 25%;">

                            </div>
                            <div class="text-danger error error-image"></div>
                        </div>
                        <div class="mb-3 row">
                            <label>Category</label>
                            <select class="selectpicker" name="category_ids[]" multiple data-live-search="true">
                                @foreach($categories  as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                            <div class="text-danger error error-category_ids"></div>
                        </div>
                        <hr>
                        <div class="mb-3 text-center">
                            <button class="btn btn-rounded btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
                            <button class="btn btn-rounded btn-primary" type="submit" id="btn-create">Create</button>
                        </div>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

{{--@endsection--}}

laravel/resources/views/admin/products/edit.blade.php
    <form data-action="{{ route('products.update',$product->id) }}" id="updateProductForm" method="post" enctype="multipart/form-data">
        @csrf
        <div class="mb-3">
            <label>Name</label>
            <input type="text" name="name" class="form-control" value="{{ $product->name }}">
            <div class="text-danger error error-name"></div>
        </div>
        <div class="mb-3">
            <label>Price</label>
            <input type="number" name="price" class="form-control" value="{{ $product->price }}">
            <div class="text-danger error error-price"></div>
        </div>
        <div class="mb-3">
            <label class="form-label">Image</label>
            <input type="file" value="" class="form-control image" name="image">
            <div class="show-image" style="width: 25%">
                <img src="{{ $product->image }}" width="100%">
            </div>
            <div class="text-danger error error-image"></div>
        </div>
        <div class="mb-3">
            <label>Quantity</label>
            <input type="number" name="quantity" class="form-control" value="{{ $product->quantity }}">
            <div class="text-danger error error-quantity"></div>
        </div>
        <div class="mb-3">
            <label>Description</label>
            <input type="text" name="description" class="form-control" value="{{ $product->description }}">
            <div class="text-danger error error-description"></div>
        </div>
        <div class="mb-3 set-height-cate">
            <label>Category</label>
            <select class="selectpicker" name="category_ids[]" multiple>
                @foreach($categories as $category)
                    <option {{$product->categories->contains('id',$category->id) ? 'selected' : ''}} value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
            <div class="text-danger error error-category_ids"></div>
        </div>
        <hr>
        <div class="mb-3 text-center">
            <button class="btn btn-rounded btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
            <button class="btn btn-rounded btn-primary" type="submit" id="btn-update">Update</button>
        </div>
    </form>

    <script>
        $(".selectpicker").selectpicker('refresh');
    </script>

laravel/resources/views/admin/products/index.blade.php
@extends('admin.Layouts.dashboard')

@section('content')

        @if (session('message'))
            <div class="alert alert-primary" role="alert">
                {{ session('message') }}
            </div>
        @endif

        <div>
            <button type="button" class="btn btn-dribbble mb-2" id="btn-add-new-product"
                    data-bs-toggle="modal" data-bs-target="#modal-form-create">
                <i class="mdi mdi-plus-circle me-1"></i>
                Create
            </button>
        </div>
            <h1>List Product</h1>

        <br>
        <div class="form-search">
            <form method="get" id="search-product">
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Name&emsp;</label>
                    <input value="{{request()->name ?? ''}}" placeholder="Name" type="text" name="name"
                           class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Price&emsp;</label>
                    <input value="{{request()->min_price ?? ''}}" placeholder="Min Price" type="number" name="min_price"
                           step="10000" min="0" class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                    <input value="{{request()->max_price ?? ''}}" placeholder="Max Price" type="number" name="max_price"
                           step="10000" min="0" class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Category</label>
                    <select class="form-select" name="category" type="text"
                            style="padding-left: 10px; margin-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                        <option value="" >Select</option>
                        @foreach($categories as $category)
                            <option
                                value="{{$category->id}}" {{ request()->category_id == $category->id ? 'selected' : '' }}>{{$category->name}}
                            </option>
                        @endforeach
                    </select>
                </div>
                <button class="btn btn-success search-product" type="submit">Search</button>

            </form>
            <div>
                <br>
                <div class="row" id="show-product" data-action-table="{{route('products.list')}}"></div>

            </div>
        </div>
        <hr>

    @include('admin.products.show')
    @include('admin.products.create')
{{--    @include('admin.products.edit')--}}

        <script src="{{asset('js/jquery.min.js')}}" defer></script>
        <script src="{{asset('js/base.js')}}" defer></script>
        <script src="{{asset('js/product.js')}}" defer></script>
        <script src="{{asset('js/toastr.js')}}"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
@endsection

laravel/resources/views/admin/products/list.blade.php
    <div class="container-fluid">

        <!-- start page title -->
        @if(session('message'))
            <div>
                <h4 class="text-primary">{{ session('message') }}</h4>
            </div>
        @endif
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
{{--                                    <th>Image</th>--}}

                                    <th style="width: 85px;text-align: center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($products) != 0)
                                    @foreach($products as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->name }}</td>
{{--                                            <td><img src="{{asset($item->image)}}"></td>--}}
{{--                                            <td><img src="{{asset('upload/images/default.jpg')}}"></td>--}}

                                            <td>
                                                <a class="btn btn-success btn-edit" data-url-edit="{{ route('products.edit', $item->id) }}">Edit</a>
                                                <a class="btn btn-warning btn-show" data-url-show="{{ route('products.show', $item->id) }}">Show</a>

                                                <form data-action="{{ route('products.destroy', $item->id) }}" method="post" style="display: inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button  class="btn btn-danger btn-delete">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $products->appends(request()->all())->links() }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>

</div>

laravel/resources/views/admin/products/show.blade.php
<div class="container modal fade" id="modal-show">
    <div class="modal-dialog">
        <div class="modal-content">
            <div style="margin: 20px 20px 20px 20px;">
                <div>
                    <h1 id="product-title"> Show Product </h1>
                </div>
                <div class="mb-3">

                </div>
                <div class="panel-group">
                    <div class="mb-2">
                        <div class="panel-heading"><strong>Name</strong></div>
                        <div class="panel-body" id="product-name"></div>
                    </div>
                    <div class="mb-2">
                        <div class="panel-heading"><strong>Price</strong></div>
                        <div class="panel-body" id="product-price"></div>
                    </div>
                    <div class="mb-2">
                        <div class="panel-heading"><strong>Describe</strong></div>

                        <option size="5" class="form-select" name="describe" id="product-description" multiple>
                        </option>

                    </div>
                    <div class="mb-2">
                        <div class="panel-heading"><strong>Quantity</strong></div>
                        <div class="panel-body" id="product-quantity"></div>
                    </div>

                    <div class="mb-2">
                        <div class="panel-heading"><strong>Category</strong></div>
{{--                        @foreach($categories as $category)--}}
{{--                            <option--}}
{{--                                value="{{$category->id}}" {{ request()->category_id == $category->id ? 'selected' : '' }}>{{$category->name}}--}}
{{--                            </option>--}}
{{--                        @endforeach--}}
                        <div class="panel-body" id="product-category"></div>
                    </div>
                    <div class="mb-2">
                        <div class="panel-heading"><strong>Image</strong></div>
                        <div class="panel-body" id="product-imaged"></div>
                        <img class="rounded bg-light image-data img-thumbnail"
                             style="max-width: 70%; height: auto;" id="product-image" src=""/>
                    </div>
                </div>
                <a class="btn btn-secondary" id="close-show" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
{{--@endsection--}}