laravel/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function (){
    Route::get('/',[RoleController::class, 'index'])->name('index');
    Route::post('/',[RoleController::class, 'store'])->name('store');
    Route::get('/create',[RoleController::class, 'create'])->name('create');
    Route::get('/show/{id}',[RoleController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[RoleController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[RoleController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[RoleController::class, 'destroy'])->name('destroy');
});

Route::name('users.')->prefix('users')->group(function (){
    Route::get('/',[UserController::class, 'index'])->name('index');
    Route::post('/',[UserController::class, 'store'])->name('store');
    Route::get('/create',[UserController::class, 'create'])->name('create');
    Route::get('/show/{id}',[UserController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[UserController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[UserController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[UserController::class, 'destroy'])->name('destroy');
});

Route::prefix('categories')->name('categories.')->group(function (){
    Route::get('/',[CategoryController::class, 'index'])->name('index');
    Route::post('/',[CategoryController::class, 'store'])->name('store');
    Route::get('/create',[CategoryController::class, 'create'])->name('create');
    Route::get('/show/{id}',[CategoryController::class, 'show'])->name('show');
    Route::get('/edit/{id}',[CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{id}',[CategoryController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[CategoryController::class, 'destroy'])->name('destroy');
});


Route::prefix('products')->name('products.')->group(function (){
    Route::get('/',[ProductController::class, 'index'])->name('index');
    Route::post('/',[ProductController::class, 'store'])->name('store');
    Route::get('/list',[ProductController::class,'list'])->name('list');
    Route::get('/show/{id}',[ProductController::class, 'show'])->name('show');
    Route::get('/create',[ProductController::class, 'create'])->name('create');
    Route::get('/edit/{id}',[ProductController::class, 'edit'])->name('edit');
    Route::post('/update/{id}',[ProductController::class, 'update'])->name('update');
    Route::delete('/destroy/{id}',[ProductController::class, 'destroy'])->name('destroy');
});

laravel/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
      'address',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function hasRoles($rolesName)
    {
        return $this->roles->contains('name', $rolesName);
    }

    public function hasPermission($permissionName)
    {
        $roles = $this->roles;
        foreach ($roles as $role) {
            if ($role->hasPermissions($permissionName)) {
                return true;
            }
        }
        return false;
    }

    public function isSupperAdmin()
    {
        return $this->hasRoles('super-admin');
    }

    public function attachRole($roleId)
    {
        return $this->roles()->attach($roleId);
    }

    public function syncRole($roleId)
    {
        return $this->roles()->sync($roleId);
    }

    public function detachRole()
    {
        return $this->roles()->detach();
    }

    public function scopeSearchWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }

    public function scopeSearchWithEmail($query, $email)
    {
        return $email ? $query->where('email', $email) : null;
    }

    public function scopeSearchWithRoleId($query, $roleId)
    {
        return $roleId ? $query->whereHas('roles', fn( $q) => $q->where('role_id', $roleId)) : null;
    }
}

laravel/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Services\RoleService;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\View;

class UserController extends Controller
{
    protected $userService;
    protected $roleService;

    public function __construct(RoleService $roleService, UserService $userService)
    {
        $this->roleService = $roleService;
        $this->userService = $userService;
        View::share('role', $this->roleService->all());
    }

    public function index(Request $request)
    {
        $users = $this->userService->search($request);
        return view("admin.users.index", compact('users'));
    }

    public function show($id)
    {
        $user = $this->userService->findById($id);
        return view("admin.users.show", compact('user'));
    }

    public function create()
    {
        $roles = $this->roleService->all();
        return view("admin.users.create",compact('roles'));
    }

    public function store(CreateUserRequest $request)
    {
        $this->userService->store($request);

        $dataCreate = $request->all();
        $dataCreate['password'] = Hash::make($request->password);

//        $user = $this->user->create($dataCreate);
        return redirect()->route('users.index')->with("message", "Create User Successfully!.");
    }

    public function edit($id)
    {
        $user = $this->userService->findById($id);
        return view("admin.users.edit", compact('user'));
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $this->userService->update($request, $id);
        return redirect()->route("users.index")->with("message", "Update User Successfully!.");
    }

    public function destroy($id)
    {
        $this->userService->destroy($id);
        return redirect()->back()->with('message', "Delete User Successfully!.");
    }
}

laravel/resources/views/admin/users/create.blade.php
@extends("admin.Layouts.dashboard")
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Create User</h4>
                </div>
            </div>
        </div>
        <div>
            <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{old('name')}}" name="name" class="form-control">

                    @error('name')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Email</label>
                    <input type="text" value="{{old('email')}}" name="email" class="form-control">

                    @error('email')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Phone</label>
                    <input type="int" value="{{old('phone')}}" name="phone" class="form-control">

                    @error('phone')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Address</label>
                    <textarea value="{{old('address')}}" name="address" class="form-control"></textarea>

                    @error('address')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Gender</label>
                    <input type="text" value="{{old('gender')}}" name="gender" class="form-control">
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option value="male">Male</option>
                        <option value="female">Female</option>

                    </select>

                    @error('gender')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Password</label>
                    <input type="password" value="{{old('password')}}" name="password" class="form-control">

                    @error('password')
                    <span class="text-danger">{{ $message }}</span>
                    @enderror

                </div>
                <div class="mb-3">
                    <label class="form-label">Role</label>
                    <br>
                    <select class="form-select" name="role_ids[]" multiple size="5">
                        @foreach($roles as $role)
                            <option value="{{$role->id}}">{{ $role->display_name }}</option>
                        @endforeach
                    </select>

                </div>
                <div>
                    <a type="button" href="{{ route("users.index") }}" class="btn btn-secondary btn-button">Back</a>
                    <button type="submit" class="btn btn-primary btn-button">Create</button>
                </div>

            </form>
        </div>



{{--        <div class="row">--}}
{{--            <div class="col-12">--}}
{{--                <div class="card">--}}
{{--                    <div class="card-body">--}}
{{--                        <form action="{{ route('users.store') }}" data-action="{{ route('users.store') }}" id="form-add" method="POST" enctype="multipart/form-data">--}}
{{--                            @csrf--}}
{{--                            <div class="modal-body">--}}

{{--                                <div class="mb-3">--}}
{{--                                    <label>Name</label>--}}
{{--                                    <input type="text" name="name" value="{{ old("name") }}" class="form-control" placeholder="Name">--}}
{{--                                </div>--}}
{{--                                <div class="mb-3">--}}
{{--                                    <label>Email address</label>--}}
{{--                                    <input type="email" name="email" value="{{ old("email") }}" class="form-control" placeholder="Email">--}}
{{--                                </div>--}}
{{--                                <div class="mb-3">--}}
{{--                                    <label>Address</label>--}}
{{--                                    <input type="text" name="address" value="{{ old("address") }}" class="form-control" placeholder="Address">--}}
{{--                                </div>--}}

{{--                                <div class="input-group input-group-static mb-4">--}}
{{--                                    <label  name="group" class="ms-0">Group</label>--}}
{{--                                    <select name="gender" class="form-control" >--}}
{{--                                        <option value="male">Male</option>--}}
{{--                                        <option value="fe-male">FeMale</option>--}}

{{--                                    </select>--}}
{{--                                    @error('gender')--}}
{{--                                    <span class="text-danger">{{ $message }}</span>--}}
{{--                                    @enderror--}}
{{--                                </div>--}}

{{--                                <div class="mb-3">--}}
{{--                                    <label>Phone</label>--}}
{{--                                    <input type="number" name="phone" value="{{ old("phone") }}" class="form-control" placeholder="Phone">--}}
{{--                                </div>--}}
{{--                                <div class="mb-3">--}}
{{--                                    <label for="password" class="form-label"> Password</label>--}}
{{--                                    <div class="input-group input-group-merge">--}}
{{--                                        <input type="password" id="password" value="{{ old("password") }}" name="password" class="form-control" placeholder="Enter your password">--}}
{{--                                        <div class="input-group-text" data-password="false">--}}
{{--                                            <span class="password-eye"></span>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                </div>--}}


{{--                                --}}{{--                                <div class="mb-3">--}}

{{--                                </div>--}}
{{--                            </div>--}}

{{--                        </form>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
    </div>
@endsection

laravel/resources/views/admin/users/edit.blade.php
@extends('admin.Layouts.dashboard')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <h4 class="page-title">Update User</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('users.update',$user->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('put')

                            <div class="modal-body">
                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" name="name" class="form-control" value="{{ $user->name }}" placeholder="Name">
                                </div>
                                <div class="mb-3">
                                    <label>Email address</label>
                                    <input type="email" name="email" class="form-control" value="{{ $user->email }}" placeholder="Email">
                                </div>

                                <div class="mb-3">
                                    <label>Address</label>
                                    <input type="text" name="address" class="form-control" value="{{ $user->address }}" placeholder="Address">
                                </div>

                                <div class="mb-3">
                                    <label>Phone</label>
                                    <input type="number" name="phone" class="form-control" value="{{ $user->phone }}" placeholder="Phone">
                                    @error('phone')
                                    <span class="alert alert-danger">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <label for="password" class="form-label">Password</label>
                                    <div class="input-group input-group-merge">
                                        <input type="password" id="password" name="password" class="form-control" placeholder="Enter your password">
                                        @error('password')
                                        <div class="alert alert-danger">
                                            <strong>{{ $message }}</strong>
                                        </div>
                                        @enderror
                                        <div class="input-group-text" data-password="false">
                                            <span class="password-eye"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a type="button" href="{{ url()->previous() }}" class="btn btn-secondary btn-button">Back</a>
                                <button type="submit" class="btn btn-primary btn-button">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/admin/users/index.blade.php
@extends("admin.Layouts.dashboard")
@section("content")
    <div class="container-fluid">

        <!-- start page title -->
        @if(session('message'))
            <div>
                <h4 class="text-primary">{{ session('message') }}</h4>
            </div>
        @endif

        <div style="padding-left: 1%">
            <div>
                <a href="{{route('users.create')}}" class="btn btn-dribbble">Create User</a>
            </div>
            <h1>User List</h1>

        </div>
        <!-- end page title -->



        <div class=" col-md-10 set-search">
            <form action="" method="get">
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Name&emsp;</label>
                    <input value="{{request()->name ?? ''}}" placeholder="Name" type="text" name="name"
                           class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display:flex">
                    <label class="form-label">Email&emsp;</label>
                    <input value="{{request()->email ?? ''}}" placeholder="@gmail.com" type="text" name="email"
                           class="form-control"
                           style="padding-left: 10px; background-color: #fff; border: 1px solid #e7ebf0;">
                </div>
                <div class="mb-3" style="display: flex">
                    <label class="form-label">Role</label>
                    <select class="form-select" name="category" type="text"
                            style="padding-left: 10px; margin-left: 20px; background-color: #fff; border: 1px solid #e7ebf0;">
                        <option value="" >Select</option>
                        @foreach($role as $item)
                            <option {{ $item->id == request('role_id') ? 'selected' : '' }} value="{{ $item->id }}">
                                {{ $item->display_name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-dribbble" style="margin-left: 5px">Search</button>
            </form>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">

                            <table class="table table-centered table-bordered w-100 dt-responsive nowrap">
                                <thead class="table-light">
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th style="width: 85px;text-align: center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @if(count($users) != 0)
                                    @foreach($users as $item)
                                        <tr>
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->phone }}</td>

                                            <td>
                                                <a href="{{route('users.edit', $item->id)}}" class="btn btn-success">Edit</a>
                                                <a href="{{ route('users.show', $item->id) }}" class="btn btn-warning">Show</a>
                                                <form action="{{ route('users.destroy', $item->id) }}" method="post" style="display: inline">
                                                    @csrf
                                                    @method('Delete')
                                                    <button  class="btn btn-danger btn-delete">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                @else
                                    <tbody>
                                    <tr>
                                        <td colspan="5" class="text-center"><span style="font-size: 25px; color: #d8d8d8">No data...</span></td>
                                    </tr>
                                    </tbody>
                                @endif
                            </table>
                            {{ $users->appends(request()->all())->links() }}
                        </div>
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    @push('scripts')
        <script src="{{asset('js/user.js')}}"></script>
    @endpush
@endsection

laravel/resources/views/admin/users/show.blade.php
@extends("admin.Layouts.dashboard")
@section("content")
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-md-4" style="margin: auto;padding: 10px;text-align: center">
                <h2 class="page-title">Detail user {{ $user->name }}</h2>

            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-md-6" style="margin: auto">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-4">Id :</dt>
                            <dd class="col-sm-8">{{ $user->id }}</dd>
                            <dt class="col-sm-4">Name :</dt>
                            <dd class="col-sm-8">{{ $user->name }}</dd>
                            <dt class="col-sm-4">Email address :</dt>
                            <dd class="col-sm-8">{{ $user->email }}</dd>
                            <dt class="col-sm-4">Phone :</dt>
                            <dd class="col-sm-8">{{ $user->phone }}</dd>
                            <dt class="col-sm-4">Role :</dt>
                            <dd class="col-sm-8">
                                @if($user->hasRoles('super-admin'))
                                    <div class="col-sm-2">
                                        <span class="badge bg-success">Super Admin</span>
                                    </div>
                                @else
                                    @foreach($user->roles as $item)
                                        <div class="col-sm-2">
                                            <span class="badge bg-success">{{ $item->display_name }}</span>
                                        </div>
                                    @endforeach
                                @endif
                            </dd>
                        </dl>
                    </div>

                </div>
                <div><br>
                    <a type="button" href="{{ url()->previous() }}" class="btn btn-primary btn-button">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection